### ISSUE TITLE
[question] what changes would you make to the code (if any)

### ISSUE THREAD

**Issue by weisk** [nikensss/nodejs_design_patterns#2]
to find all occurrences of 'her' ?

**Comment by nikensss** [comment]
https://github.com/nikensss/nodejs_design_patterns/blob/920cb9b6fbdd79e780f30bc2c8be9088124125b9/src/index.js#L6

I would modify the constructor call with `/her/g` instead of `'if'`.

**Comment by weisk** [comment]
Very well!
